version: 2.1
jobs:
  deploy:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install awscli
          command: |
            sudo pip install awsebcli --upgrade
      - run:
          name: Create AWS credentials
          command: |
            mkdir ~/.aws
            touch ~/.aws/config
            chmod 777 ~/.aws/config
            echo "[profile eb-cli]" > ~/.aws/config
            echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/config
            echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/config
      - run:
          name: deploy
          command: |
            eb use Therapigeonbugreporterms-env --profile eb-cli
            eb deploy -v --profile eb-cli

workflows:
  deploy:
    jobs:
      - hold:
          type: approval
      - deploy:
          requires: 
            - hold
          context: aws
          filters:
            branches:
              only:
                - master