version: 2.1
jobs:
  deploy:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install awscli and deploy
          command: |
            sudo pip install awsebcli --upgrade
            eb deploy Therapigeonbugreporterms-env

workflows:
  deploy:
    jobs:
      - hold:
          type: approval
      - deploy:
          requires: 
            - hold
          context: aws
          filters:
            branches:
              only:
                - master