version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.3.1
  aws-eb-cli: speakable-org/aws-eb-cli@1.0.0
jobs:
  build-and-test:
    executor:
      name: aws-eb-cli/default
    steps:
      - checkout
      - aws-eb-cli/with-cache:
          steps:
            - run:
                name: Deploying
                command: eb deploy Therapigeonbugreporterms-env

workflows:
  build-and-test:
    jobs:
      - hold:
          type: approval
      - build-and-test:
          requires: 
            - hold
          context: aws
          filters:
            branches:
              only:
                - master