version: 2
jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
      - checkout
      - run:
        name: Installing deployment dependencies
        command: |
          sudo pip install awsebcli --upgrade
      - run:
        name: Deploying
        command: eb deploy Therapigeonbugreporterms-env

workflows:
  build-and-test:
    jobs:
      - hold:
          type: approval
      - build-and-test:
          requires: 
            - hold
          context: aws
          filters:
            branches:
              only:
                - master